--- 
jwtExpiration: 86400
jwtSecret: me.zhulin
server: 
  servlet: 
    contextPath: /api
spring: 
  datasource: 
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    in.itialization-mode: always
    password: root
    platform: postgres
    url: "jdbc:postgresql://localhost/postgres"
    username: postgres
  jpa: 
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate: 
      ddl-auto: create
    properties: 
      hibernate: 
        temp: 
          use_jdbc_metadata_defaults: false;
    show-sql: false
  queries: 
    roles-query: "select email, role from users where email=?"
    users-query: "select email, password, active from users where email=?"